-- Attendance-IIITNR Additive Schema Migration File
-- Run this script in your Supabase SQL Editor to initialize the required tables.

-- 1. Ensure teachers table exists
CREATE TABLE IF NOT EXISTS teachers (
    teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure students table exists
CREATE TABLE IF NOT EXISTS students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    face_embedding JSONB DEFAULT NULL,
    voice_embedding JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects table (associated with a teacher, includes soft-deletion/archival)
CREATE TABLE IF NOT EXISTS subjects (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    subject_code TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Subject-Students roster table (explicit student enrollment per subject)
CREATE TABLE IF NOT EXISTS subject_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_subject_student UNIQUE (subject_id, student_id)
);

-- 5. Attendance Sessions table (class attendance event)
CREATE TABLE IF NOT EXISTS attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT REFERENCES subjects(subject_id) ON DELETE CASCADE,
    teacher_id BIGINT REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    session_date DATE DEFAULT CURRENT_DATE,
    session_time TIMESTAMPTZ DEFAULT NOW(),
    method TEXT DEFAULT 'face',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Attendance Records table (individual attendance log for every enrolled student per session)
CREATE TABLE IF NOT EXISTS attendance_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES attendance_sessions(session_id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(student_id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('present', 'absent')),
    method TEXT DEFAULT 'face',
    confidence_score FLOAT DEFAULT NULL,
    marked_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_session_student UNIQUE (session_id, student_id)
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_subjects_teacher ON subjects(teacher_id);
CREATE INDEX IF NOT EXISTS idx_subject_students_subject ON subject_students(subject_id);
CREATE INDEX IF NOT EXISTS idx_subject_students_student ON subject_students(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_subject ON attendance_sessions(subject_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_session ON attendance_records(session_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_student ON attendance_records(student_id);
